### ISSUE TITLE
Не могу скачать большой файл

### ISSUE THREAD

**Issue by ndk** [BayRinat/simple_http_server#1]
Сгенерировал файл:
fallocate -l 10G test.img

Пытаюсь скачать через сервер и получаю в логах:
std::bad_alloc

Хммм, чтобы это могло быть?

**Comment by BayRinat** [comment]
Из-за переполнения length. Поправлю.

**Comment by bayrinat** [comment]
Из-за переполнения length всё. На prepare буффера вылетает ошибка. Поправлю, но уже не сегодня.

**Comment by ndk** [comment]
Хорошо, давайте тогда подумаем о том, что файл может оказаться бесконечным.

**Comment by bayrinat** [comment]
Нужно читать файл по частям, например прочитали 5 MB и поставили на асинхронную отправку. А дальше уже пользователь решает, когда ему остановить процесс скачивания.

**Comment by ndk** [comment]
Именно! :)

**Comment by bayrinat** [comment]
К концу недели постараюсь поправить. Еще какие-либо ошибки/недочеты есть?

**Comment by ndk** [comment]
Скажем так, вопросы и замечания есть, но они будут отличной темой для разговора на собеседовании.

**Comment by bayrinat** [comment]
залил новую версию

**Comment by ndk** [comment]
Не совсем верно. Во-первых, скорость работы диска, обычно, выше скорости сетки, те поведение будет сродни вычитыванию файла в память полностью. Во-вторых, в некоторых ситуациях может произойти так, что блоки данных отправятся в неправильной последовательности.

**Comment by ndk** [comment]
P.S. Ещё можно посмотреть что такое лямбды, зачем их придумали и взамен чего их предлагается использовать.

**Comment by bayrinat** [comment]
Согласен с замечаниями. Сейчас в отпуске, как только будет доступ к компьютеру - поправлю.

**Comment by bayrinat** [comment]
Поправил
